# This workflow should cleanup everything unneeded from the template project

name: Cleanup after create
on:
  push:
    branches:
      - main # maybe all to run "tests" on every change?

env:
  TEMPLATE_NAME: "cpp_boilerplate_project"
  TEMPLATES_PATH: ".github/template"
  
jobs:

  template-cleanup:
    name: Cleanup after create
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2.4.0

      - name: Get organization and project name 
        run: |
          echo "NEW_ORG=${{ github.actor }}" >> $GITHUB_ENV
          echo "NEW_PROJECT=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - uses: octokit/request-action@v2.x
        id: get_repo_meta
        with:
          route: GET /repos/{owner}/{repo}
          owner: ${{ env.NEW_ORG }}
          repo: ${{ env.NEW_PROJECT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Rename all cpp_starter_project occurences to current repository and remove this workflow
      - name: Insert new org and project
        run: |
          # rename the CMake project to match the github project
          sed -i "s/myproject/${{ github.event.repository.name }}/g" CMakeLists.txt
          
          # fill in placeholders of readme and move it into place
          sed -i "s/%%myorg%%/${{ env.NEW_ORG }}/g" ${{ env.TEMPLATES_PATH }}/README.md
          sed -i "s/%%myproject%%/${{ env.NEW_PROJECT }}/g" ${{ env.TEMPLATES_PATH }}/README.md
          # ToDo get this info from the repo description
          sed -i "s/%%description%%/This project does stuff/g" ${{ env.TEMPLATES_PATH }}/README.md
          cp ${{ env.TEMPLATES_PATH }}/README.md README.md
          
      - name: Remove unwanted files
        run: |
          xargs rm -r < ${{ env.TEMPLATES_PATH }}/removal-list
          xargs ls < ${{ env.TEMPLATES_PATH }}/removal-list || echo "ls failed"
        
      - name: Just print touched files
        run: |
          # ToDo maybe check if the diff is like we expected?
          git diff CMakeLists.txt
          # diffing the template is more readable then the real readme
          git diff ${{ env.TEMPLATES_PATH }}/README.md

      - name: Clean up before commit and push
        run: |
          rm -rf ${{ env.TEMPLATES_PATH }}

          # Can we get that from a variabl?
          # Remove this workflow as it has fulfilled its purpose
          rm -rf .github/workflows/cleanup-after-create.yml

      - uses: EndBug/add-and-commit@v4
        # only commit and push if we are not a template project anymore!
        if: fromJson(steps.get_repo_meta.outputs.data).is_template != true
        with:
          author_name: Cleanup Robot
          author_email: template.cleanup@example.com
          message: 'Cleanup template and initialize repository'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
